/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-bg": "rgb(var(--success-bg) / <alpha-value>)",
        "on-primary-container": "#fdfcff",
        "text-secondary": "rgb(var(--text-secondary) / <alpha-value>)",
        "secondary-fixed-dim": "#adc6ff",
        "warning": "#F5A623",
        "error-text": "rgb(var(--error-text) / <alpha-value>)",
        "on-secondary": "#ffffff",
        "tertiary": "rgb(var(--tertiary) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
        "tertiary-fixed": "#b0ecff",
        "error-container": "#ffdad6",
        "primary-dark": "#0A63A8",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        "primary-light": "#0B8FEF",
        "on-secondary-fixed-variant": "#204583",
        "secondary-container": "#98b9fe",
        "tertiary-container": "#008099",
        "primary-fixed": "#d2e4ff",
        "inverse-primary": "#a1c9ff",
        "on-tertiary-container": "#fbfdff",
        "tertiary-fixed-dim": "#3fd7fc",
        "success": "#18A874",
        "surface-soft-blue": "rgb(var(--surface-soft-blue) / <alpha-value>)",
        "surface-tint": "#0060a8",
        "surface-variant": "#d7e3ff",
        "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
        "surface-dim": "#c9daff",
        "on-primary-fixed-variant": "#004880",
        "error-bg": "rgb(var(--error-bg) / <alpha-value>)",
        "surface-light-blue": "rgb(var(--surface-light-blue) / <alpha-value>)",
        "border-subtle": "rgb(var(--border-subtle) / <alpha-value>)",
        "secondary": "#3b5d9c",
        "on-error-container": "#93000a",
        "surface": "rgb(var(--surface) / <alpha-value>)",
        "on-secondary-container": "#234885",
        "success-text": "rgb(var(--success-text) / <alpha-value>)",
        "surface-bright": "rgb(var(--surface) / <alpha-value>)",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a1c9ff",
        "on-background": "rgb(var(--on-background) / <alpha-value>)",
        "outline": "#717783",
        "background": "rgb(var(--background) / <alpha-value>)",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#004e5e",
        "outline-variant": "#c0c7d3",
        "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
        "inverse-on-surface": "#ecf0ff",
        "warning-bg": "rgb(var(--warning-bg) / <alpha-value>)",
        "on-tertiary-fixed": "#001f27",
        "on-error": "#ffffff",
        "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
        "on-primary-fixed": "#001c38",
        "on-secondary-fixed": "#001a41",
        "primary": "rgb(var(--primary) / <alpha-value>)",
        "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
        "error": "#E05252",
        "warning-text": "rgb(var(--warning-text) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
        "inverse-surface": "#12305b",
        "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        title: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        price: ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "price-lg": ["Inter", "sans-serif"],
        "price-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "price-lg": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "price-md": ["16px", { lineHeight: "20px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
