import { Product } from '../types/product';

export const DUMMY_PRODUCTS: Product[] = [
  // 1. Skincare & Beauty
  {
    id: 'prod-skii-essence',
    name: 'SK-II Facial Treatment Essence 230ml',
    originalNameJp: 'エスケーツー フェイシャルトリートメント エッセンス',
    category: 'skincare',
    categoryLabel: 'Skincare & Beauty',
    storeBadge: 'Ginza Boutique Exclusive',
    storeLocation: 'Matsuya Ginza Flagship',
    tag: 'Holy Grail Beauty',
    isReadyTokyo: true,
    priceJpy: 22000,
    priceIdr: 2493000,
    weightG: 450,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqt7lJrjGQdUbIhA7FzFKqYZkXO_erhyYaXjvIz9aJlhnofFQ9yyEqTJRg1I7hQ4JM8WiUDKMBJRNeDcBc07lA7FCJNJA0sfYsmIYZVUrHQzq_9OOlW-rzvERWQgE0pT3tYnu7XeMNPyJ9hpkZriHTeW-tUG_93t1TV496sYNuR_HpM3k_f5opN7Moa5lx-Goc1XJE1NWUddxoCUkso2BjlMAeRhHAimscMDDLLusGf6xSSR4N8C6K',
    description: 'Essence ikonik Jepang dengan kandungan lebih dari 90% Pitera™ murni untuk kulit bening berkilau sebening kristal.',
    features: ['100% Original Segel Resmi Jepang', 'Dilengkapi Struk Departemen Store Matsuya', 'Exp date paling baru'],
    stockStatus: 'available',
    stockLabel: 'Ready Tokyo Hub',
    rating: 4.95,
    reviewCount: 142,
  },
  {
    id: 'prod-melano-cc',
    name: 'Rohto Melano CC Premium Essence 20ml',
    originalNameJp: 'メラノCC プレミアム美容液',
    category: 'skincare',
    categoryLabel: 'Skincare & Beauty',
    storeBadge: 'Don Quijote Pick',
    storeLocation: 'Don Quijote Shibuya',
    tag: 'Donki Best Seller',
    isReadyTokyo: true,
    priceJpy: 1280,
    priceIdr: 195000,
    weightG: 100,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAJTWXYZ8kd_2LdA4yIoLccRs5e9tth0JMFaZWHOVLRTo6QKZaMuB4g29Qmo0_xblgP3KwP3I0Iguo_cHGbzEQTlF8Muy2IaUf-IBjQKyx1EBRkWoFqIWs6bcGciMdq_sCLFsgV9kCgAAUKjiz2O13tmgPAyjISMcNQzDkR6tYd4ILmg_3EB1Q_f70uU4at3JNx5PhWs1KCqEojMvQv8lgoTxl1QJiuB4S0XE94l643vL4HF7eGPq2',
    description: 'Serum vitamin C no. 1 di drugstore Jepang untuk memudarkan noda gelap & mencerahkan wajah.',
    features: ['Formula Vitamin C murni stabil', 'Mencegah breakout & inflamasi', 'Segel resmi drugstore Jepang'],
    stockStatus: 'available',
    stockLabel: 'Ready Tokyo',
    rating: 4.95,
    reviewCount: 154,
  },
  {
    id: 'prod-fino-hair-mask',
    name: 'Shiseido Fino Premium Touch Hair Mask 230g',
    originalNameJp: 'フィーノ プレミアムタッチ ヘアマスク',
    category: 'skincare',
    categoryLabel: 'Skincare & Beauty',
    storeBadge: 'Matsukiyo Top 1',
    storeLocation: 'Matsumoto Kiyoshi Shinjuku',
    tag: 'Viral Beauty',
    isReadyTokyo: true,
    priceJpy: 980,
    priceIdr: 155000,
    weightG: 320,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqt7lJrjGQdUbIhA7FzFKqYZkXO_erhyYaXjvIz9aJlhnofFQ9yyEqTJRg1I7hQ4JM8WiUDKMBJRNeDcBc07lA7FCJNJA0sfYsmIYZVUrHQzq_9OOlW-rzvERWQgE0pT3tYnu7XeMNPyJ9hpkZriHTeW-tUG_93t1TV496sYNuR_HpM3k_f5opN7Moa5lx-Goc1XJE1NWUddxoCUkso2BjlMAeRhHAimscMDDLLusGf6xSSR4N8C6K',
    description: 'Masker rambut no. 1 di Cosme Jepang dengan 6 bahan serum nutrisi untuk perbaikan rambut rusak secara instan.',
    features: ['Cosme Hall of Fame Winner', 'Royal Jelly EX + Lipidure', 'Authentic Japan Domestic Market version'],
    stockStatus: 'available',
    stockLabel: 'Ready Tokyo',
    rating: 4.96,
    reviewCount: 312,
  },

  // 2. Makanan & Minuman
  {
    id: 'prod-tokyo-banana',
    name: 'Tokyo Banana Classic Custard Box of 8',
    originalNameJp: '東京ばな奈「見ぃつけたっ」',
    category: 'makanan',
    categoryLabel: 'Makanan & Minuman',
    storeBadge: 'Haneda Airport Fresh',
    storeLocation: 'Haneda Airport International Hub',
    tag: 'Fresh Batch',
    isReadyTokyo: true,
    priceJpy: 1180,
    priceIdr: 175000,
    weightG: 450,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7Nx3ZjGzCrDjDGaEgZo11qD9WQt4dg_RQNkhZ05r8Kkfd1UKQVVY9W30w-HYANmgnKK2GIQ3k5dHSI2KYEqOlFQibC3BPpEhMmoxwa28LlRmnPCABQU5yUTlPluc6Hdztl8q-vm3wW1KprqZJ94pOnAnPYPrGBibbmxOdRbgLJnp90uof_QA5Cqe0j3pTAb2qghK68ratsqia-nh4qMFluJaevLVBnEYiNygVr7jUtU-NvuxG8hAb',
    description: 'Omiyage khas Tokyo paling populer dengan bolu lembut isi krim pisang custard manis legit.',
    features: ['Freshly baked Tokyo Batch', 'Pengiriman cepat via Handcarry', 'Termasuk original gift bag'],
    stockStatus: 'available',
    stockLabel: 'Batch #48 & #49',
    rating: 4.88,
    reviewCount: 210,
  },
  {
    id: 'prod-shiroi-koibito',
    name: 'Ishiya Shiroi Koibito White Chocolate 18 Pcs',
    originalNameJp: '白い恋人 18枚入 ホワイト',
    category: 'makanan',
    categoryLabel: 'Makanan & Minuman',
    storeBadge: 'Airport Tax Free Exclusive',
    storeLocation: 'Kansai Intl Airport KIX',
    tag: 'Hokkaido Famous',
    isReadyTokyo: true,
    priceJpy: 1512,
    priceIdr: 220000,
    weightG: 380,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4lfJU2aFsekhcSUyUU9vzzBfRXVvBHs7ib7np4W-6OLsKJXwowXdZFc3n9SNzzA-HUq62VGWQSxDzX0iMnVZHC3NavbT0mAPARSgBupyCTTOUIKp28CFkTiribQ7AsVH6WHtFZcKhAJ-sgX9Fjb14E54_T2A669MEN6dGVtNaW3_Ai0sPgAd0UFl8eqonxwRwKPlsi5PWxc-nGh2LAYMeSi-B-jg6rvH-oEmph9UpTSjwe9Q1i3Rn',
    description: 'Kue lidah kucing mentega renyah khas Hokkaido dengan isian cokelat putih lembut meleleh di mulut.',
    features: ['Hokkaido Pure Butter', 'Aluminium foil protective tin', 'Best consumed chilled'],
    stockStatus: 'available',
    stockLabel: 'Batch #49 Kansai',
    rating: 4.98,
    reviewCount: 188,
  },

  // 3. Vitamin & Kesehatan
  {
    id: 'prod-dhc-vitamin-c',
    name: 'DHC Vitamin C Hard Capsule 60 Days Supply',
    originalNameJp: 'DHC ビタミンC ハードカプセル 60日分',
    category: 'kesehatan',
    categoryLabel: 'Vitamin & Kesehatan',
    storeBadge: 'Drugstore Top Pick',
    storeLocation: 'Matsumoto Kiyoshi Ginza',
    tag: 'Daily Supplement',
    isReadyTokyo: true,
    priceJpy: 480,
    priceIdr: 75000,
    weightG: 80,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDYFw4wGXwCFMb0eFdDgRQPdiXDdGkmq8excjFWU1-M3D1t9zyxFmYRsIErYlkV5OdI2wGvFNQHV6meKqQn5Cp3X5xJWLtGqhlMuloSBEA1kIYlhpdR5gxctI6jc_p8rs-ACmxS4npdLrbCMm4m-IODdHA7aZuQ3SXpUw_aIWMHZ9zkiu4MHlBB5mVJUZvvXAkKQ_j-i0upZs4Vb71dColRKaFyKv4zJiuTRiDAYyBxTTfpIuPGn_EO',
    description: 'Suplemen vitamin C no. 1 di Jepang diperkaya Vitamin B2 untuk menjaga imunitas dan kecerahan kulit.',
    features: ['1000mg Vitamin C per serving', 'Kemasan ziplock higienis', 'Produksi resmi DHC Jepang'],
    stockStatus: 'available',
    stockLabel: 'Ready Stock',
    rating: 4.9,
    reviewCount: 110,
  },
  {
    id: 'prod-rohto-lycee',
    name: 'Rohto Lycee Eye Drops Contact Lens Formula',
    originalNameJp: 'ロートリセ コンタクトb',
    category: 'kesehatan',
    categoryLabel: 'Vitamin & Kesehatan',
    storeBadge: 'Drugstore Pick',
    storeLocation: 'Bic Camera Shinjuku Drug Section',
    tag: 'Comfort Eyes',
    isReadyTokyo: true,
    priceJpy: 748,
    priceIdr: 120000,
    weightG: 80,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDYFw4wGXwCFMb0eFdDgRQPdiXDdGkmq8excjFWU1-M3D1t9zyxFmYRsIErYlkV5OdI2wGvFNQHV6meKqQn5Cp3X5xJWLtGqhlMuloSBEA1kIYlhpdR5gxctI6jc_p8rs-ACmxS4npdLrbCMm4m-IODdHA7aZuQ3SXpUw_aIWMHZ9zkiu4MHlBB5mVJUZvvXAkKQ_j-i0upZs4Vb71dColRKaFyKv4zJiuTRiDAYyBxTTfpIuPGn_EO',
    description: 'Tetes mata bernutrisi khusus pemakai softlens dan mata lelah terpapar layar digital.',
    features: ['Vitamin B12 pink essence', 'Bisa dipakai langsung saat softlens terpasang', 'Botol mungil ergonomis'],
    stockStatus: 'available',
    stockLabel: 'Ready Stock',
    rating: 4.87,
    reviewCount: 92,
  },

  // 4. Fashion & Brand
  {
    id: 'prod-onitsuka-mexico66',
    name: 'Onitsuka Tiger Mexico 66 SD - Japan Made',
    originalNameJp: 'オニツカタイガー • Fashion',
    category: 'fashion',
    categoryLabel: 'Fashion & Brand',
    storeBadge: 'Ready Tokyo Store',
    storeLocation: 'Ginza Flagship',
    tag: 'Nippon Made Ginza',
    isReadyTokyo: true,
    priceJpy: 18700,
    priceIdr: 2057000,
    weightG: 850,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDIGdgGrOiOZ3eWELPtu9WRNwq5_Lcl92tCuPamRm8tfRzs5Hbq0yJ03GdKYYXLC90_Grz2uegGjINv8f9EdpgF3QhGc1GtcfegEejgNLWGYsz41DUUkWuBJ54sENYheHHpVq8r9p2NB39eeID2gSos_euyoamVGgE7JpxHKbqCeOFRUMZ_CrjSRguT0rschEzM9A-jSMSRvUhuy7adOhG2WIcGa7YJHkK-k-bJng1yCvezYmPVFAr2',
    description: 'Kulit asli premium diproduksi pengrajin Kobe, insole GEL peredam empuk, packaging box edisi eksklusif Tokyo.',
    features: ['100% Handcrafted in Japan', 'Official Store Receipt included', 'Custom Size Request available'],
    stockStatus: 'available',
    stockLabel: 'Size Request',
    rating: 4.9,
    reviewCount: 48,
  },

  // 5. Elektronik
  {
    id: 'prod-sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Headphones (Japan Domestic)',
    originalNameJp: 'ソニー ワイヤレスノイズキャンセリングステレオヘッドセット',
    category: 'elektronik',
    categoryLabel: 'Elektronik',
    storeBadge: 'Yodobashi Akihabara',
    storeLocation: 'Yodobashi Camera Akiba',
    tag: 'Audio Best',
    isReadyTokyo: true,
    priceJpy: 48400,
    priceIdr: 5490000,
    weightG: 700,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDIGdgGrOiOZ3eWELPtu9WRNwq5_Lcl92tCuPamRm8tfRzs5Hbq0yJ03GdKYYXLC90_Grz2uegGjINv8f9EdpgF3QhGc1GtcfegEejgNLWGYsz41DUUkWuBJ54sENYheHHpVq8r9p2NB39eeID2gSos_euyoamVGgE7JpxHKbqCeOFRUMZ_CrjSRguT0rschEzM9A-jSMSRvUhuy7adOhG2WIcGa7YJHkK-k-bJng1yCvezYmPVFAr2',
    description: 'Headphone noise cancelling terbaik dunia dengan kualitas suara Hi-Res Audio dan garansi toko resmi Yodobashi.',
    features: ['Industry Leading Noise Cancelling', 'Garansi Struk Resmi Yodobashi', 'Bebas Bea Cukai Pajak Kargo'],
    stockStatus: 'available',
    stockLabel: 'Pre-order Khusus',
    rating: 4.98,
    reviewCount: 29,
  },

  // 6. Ibu & Anak
  {
    id: 'prod-pigeon-magmag',
    name: 'Pigeon MagMag All-in-One Training Straw Cup',
    originalNameJp: 'ピジョン マグマグコロン セット',
    category: 'ibu_anak',
    categoryLabel: 'Ibu & Anak',
    storeBadge: 'Akachan Honpo Osaka',
    storeLocation: 'Akachan Honpo Umeda',
    tag: 'BPA Free JP',
    isReadyTokyo: true,
    priceJpy: 2200,
    priceIdr: 320000,
    weightG: 250,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7Nx3ZjGzCrDjDGaEgZo11qD9WQt4dg_RQNkhZ05r8Kkfd1UKQVVY9W30w-HYANmgnKK2GIQ3k5dHSI2KYEqOlFQibC3BPpEhMmoxwa28LlRmnPCABQU5yUTlPluc6Hdztl8q-vm3wW1KprqZJ94pOnAnPYPrGBibbmxOdRbgLJnp90uof_QA5Cqe0j3pTAb2qghK68ratsqia-nh4qMFluJaevLVBnEYiNygVr7jUtU-NvuxG8hAb',
    description: 'Gelas latihan minum bayi bertahap standar keamanan Jepang tanpa bocor dan bahan tahan banting.',
    features: ['100% BPA Free Food Grade', 'Anti tumpah & sedotan lembut', 'Original Akachan Honpo'],
    stockStatus: 'available',
    stockLabel: 'Ready Kansai',
    rating: 4.94,
    reviewCount: 75,
  },

  // 7. Rumah Tangga
  {
    id: 'prod-hario-v60',
    name: 'Hario V60 Ceramic Coffee Dripper 02 White Japan Made',
    originalNameJp: 'ハリオ V60 透過ドリッパー02 セラミック',
    category: 'rumah_tangga',
    categoryLabel: 'Rumah Tangga',
    storeBadge: 'Tokyu Hands Shibuya',
    storeLocation: 'Hands Shibuya Store',
    tag: 'Made in Arita',
    isReadyTokyo: true,
    priceJpy: 2500,
    priceIdr: 360000,
    weightG: 450,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4lfJU2aFsekhcSUyUU9vzzBfRXVvBHs7ib7np4W-6OLsKJXwowXdZFc3n9SNzzA-HUq62VGWQSxDzX0iMnVZHC3NavbT0mAPARSgBupyCTTOUIKp28CFkTiribQ7AsVH6WHtFZcKhAJ-sgX9Fjb14E54_T2A669MEN6dGVtNaW3_Ai0sPgAd0UFl8eqonxwRwKPlsi5PWxc-nGh2LAYMeSi-B-jg6rvH-oEmph9UpTSjwe9Q1i3Rn',
    description: 'Dripper keramik Arita-yaki legendaris buatan tangan pengrajin porselen Jepang untuk hasil pour-over kopi sempurna.',
    features: ['Keramik porselen Arita asli', 'Spiral ribs ekstraksi maksimal', 'Armor box bubble pack included'],
    stockStatus: 'available',
    stockLabel: 'Ready Stock',
    rating: 4.97,
    reviewCount: 63,
  },

  // 8. Jepang Character
  {
    id: 'prod-chiikawa-keychain',
    name: 'Chiikawa Official Mascot Plush Keychain',
    originalNameJp: 'ちいかわ ぷちミニマスコット',
    category: 'karakter',
    categoryLabel: 'Jepang Character',
    storeBadge: 'Chiikawa Land Tokyo',
    storeLocation: 'Kiddy Land Harajuku',
    tag: 'Trending Japan Character',
    isReadyTokyo: true,
    priceJpy: 1650,
    priceIdr: 245000,
    weightG: 90,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz24790W_AVAWJPkCbZyRtLhaRW7I2fZ3vNl6lbuXRAAo7hr0AiksrQpI3RJoJrUqbFKcRJKncb3k8UgqJ7nacFfp3KHPmvsbfe6DaAO1DdkChXw3BkCsLibG835eBbVafa_BEqWkeD95VoOcyQ7PANlUjBmaGnx7nFAdlMClcpfNuVkCwaXtLVzwvglQSzYiySthmOQWgTnuQcRTof67Fch3QXRH8YabvwZ0PT8ebCmH1Fb-jYb9i',
    description: 'Gantungan kunci boneka Chiikawa karakter no. 1 paling viral di Jepang saat ini dengan tag toko resmi Chiikawa Land.',
    features: ['Original Chiikawa Land Tag', 'Bahan bulu super lembut lembut', 'Langsung dari Harajuku'],
    stockStatus: 'limited',
    stockLabel: 'Sisa 3 Pcs',
    rating: 5.0,
    reviewCount: 182,
  },

  // 9. Anime & Hobi
  {
    id: 'prod-gojo-jujutsu',
    name: 'Jujutsu Kaisen Gojo Jump Shop Exclusive Standee',
    originalNameJp: '呪術廻戦 ジャンプショップ限定',
    category: 'anime',
    categoryLabel: 'Anime & Hobi',
    storeBadge: 'Akihabara Rare',
    storeLocation: 'Jump Shop Tokyo Dome City',
    tag: 'Jump Shop Limited',
    isReadyTokyo: true,
    priceJpy: 2400,
    priceIdr: 340000,
    weightG: 180,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDYBRdHxD7RVP_TtZu2Z4WEx2gfxHtp43e65O3aC3tKJ8S4oyyFtPFIPTsMxSH5lKFKEdLrqNluZ8DrR-lw_mhivBmZFXf4f1FsAASWhIyxt7pBvYBOUTZ-R82UFGY1Za-1AAQo7qrHV23XY_D0iQbrupVck0zAOtpDHrz82hZml_fjV91FnwuePUHBFmtx-lskVS-17uRvnazzs8_v6RDAvLR-BpGx508q3oZW1VxcUhTXLLOKy8l',
    description: 'Stok langsung dari Toko Jump Shop Tokyo Dome City. Dilengkapi segel hologram resmi Toho Animation.',
    features: ['Original Toho Animation Hologram', 'Exclusive Acrylic Art Board', 'Bubble wrapped double layer'],
    stockStatus: 'limited',
    stockLabel: 'Sisa 3 Slot',
    rating: 5.0,
    reviewCount: 39,
  },
  {
    id: 'prod-pokemon-center',
    name: 'Pokemon Center Shibuya Special Pikachu Plush',
    originalNameJp: 'ポケモンセンターシブヤ限定',
    category: 'anime',
    categoryLabel: 'Anime & Hobi',
    storeBadge: 'Pokemon Center Exclusive',
    storeLocation: 'Parco Shibuya 6F',
    tag: 'Limited Shibuya Edition',
    isReadyTokyo: false,
    priceJpy: 3300,
    priceIdr: 475000,
    weightG: 280,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz24790W_AVAWJPkCbZyRtLhaRW7I2fZ3vNl6lbuXRAAo7hr0AiksrQpI3RJoJrUqbFKcRJKncb3k8UgqJ7nacFfp3KHPmvsbfe6DaAO1DdkChXw3BkCsLibG835eBbVafa_BEqWkeD95VoOcyQ7PANlUjBmaGnx7nFAdlMClcpfNuVkCwaXtLVzwvglQSzYiySthmOQWgTnuQcRTof67Fch3QXRH8YabvwZ0PT8ebCmH1Fb-jYb9i',
    description: 'Boneka Pikachu grafiti Shibuya berkolaborasi dengan seniman Jepang modern. Hanya dijual di Shibuya Parco.',
    features: ['Original Pokemon Center Tag', 'Graffiti Art Pattern Exclusive', 'Bebas debu sealed plastic packaging'],
    stockStatus: 'limited',
    stockLabel: 'Sisa 2 Pcs',
    rating: 4.92,
    reviewCount: 64,
  },

  // 10. Lainnya
  {
    id: 'prod-starbucks-reserve-tumbler',
    name: 'Starbucks Reserve Roastery Tokyo Limited Sakura Tumbler',
    originalNameJp: 'スターバックス リザーブ ロースタリー 東京 限定タンブラー',
    category: 'lainnya',
    categoryLabel: 'Lainnya',
    storeBadge: 'Nakameguro Exclusive',
    storeLocation: 'Starbucks Reserve Nakameguro',
    tag: 'Limited Edition JP',
    isReadyTokyo: true,
    priceJpy: 4950,
    priceIdr: 685000,
    weightG: 350,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7Nx3ZjGzCrDjDGaEgZo11qD9WQt4dg_RQNkhZ05r8Kkfd1UKQVVY9W30w-HYANmgnKK2GIQ3k5dHSI2KYEqOlFQibC3BPpEhMmoxwa28LlRmnPCABQU5yUTlPluc6Hdztl8q-vm3wW1KprqZJ94pOnAnPYPrGBibbmxOdRbgLJnp90uof_QA5Cqe0j3pTAb2qghK68ratsqia-nh4qMFluJaevLVBnEYiNygVr7jUtU-NvuxG8hAb',
    description: 'Tumbler edisi terbatas musim semi hanya dijual di Starbucks Reserve Roastery Tokyo (Nakameguro).',
    features: ['Official Nakameguro Gift Box', 'Thermal vacuum insulation', 'Struk resmi Starbucks JP'],
    stockStatus: 'limited',
    stockLabel: 'Sisa 1 Pcs',
    rating: 4.96,
    reviewCount: 41,
  },
];
