import { FlightBatch } from '../types/batch';

export const FLIGHT_BATCHES: FlightBatch[] = [
  {
    id: 'batch-48',
    batchNumber: 48,
    title: 'Batch Tokyo Spring Kloter 1',
    route: 'Haneda (HND) ➔ Soekarno Hatta (CGK)',
    flightCode: 'NH855',
    departureCity: 'Tokyo',
    destinationCity: 'Jakarta',
    status: 'filling',
    statusBadge: 'Kuota 85% Penuh',
    cutOffDate: '28 Maret 2025',
    cutOffTime: '21:00 WIB',
    shoppingPeriod: '29 - 30 Mar 2025',
    domesticDeliveryDate: '3 April 2025',
    totalQuotaKg: 100,
    usedQuotaKg: 85,
    remainingKg: 15,
    usedPercentage: 85,
    highlightNote: 'Pengantaran kurir Paxel & JNE YES langsung dari Bandara Soekarno Hatta',
  },
  {
    id: 'batch-49',
    batchNumber: 49,
    title: 'Batch Kansai: Osaka & Kyoto',
    route: 'Kansai Intl (KIX) ➔ Soekarno Hatta (CGK)',
    flightCode: 'GA889',
    departureCity: 'Osaka',
    destinationCity: 'Jakarta',
    status: 'open',
    statusBadge: 'Pendaftaran Dibuka',
    cutOffDate: '5 April 2025',
    cutOffTime: '22:00 WIB',
    shoppingPeriod: '6 - 8 Apr 2025',
    domesticDeliveryDate: '11 April 2025',
    totalQuotaKg: 100,
    usedQuotaKg: 35,
    remainingKg: 65,
    usedPercentage: 35,
    highlightNote: 'Khusus snack Uji Matcha, Dotonbori Souvenirs, & Vintage Designer Goods',
  },
  {
    id: 'batch-50',
    batchNumber: 50,
    title: 'Batch Golden Week Special Tokyo',
    route: 'Narita (NRT) ➔ Soekarno Hatta (CGK)',
    flightCode: 'JL725',
    departureCity: 'Tokyo',
    destinationCity: 'Jakarta',
    status: 'open',
    statusBadge: 'Early Bird Slot',
    cutOffDate: '20 April 2025',
    cutOffTime: '20:00 WIB',
    shoppingPeriod: '22 - 25 Apr 2025',
    domesticDeliveryDate: '28 April 2025',
    totalQuotaKg: 120,
    usedQuotaKg: 20,
    remainingKg: 100,
    usedPercentage: 17,
    highlightNote: 'Kargo besar & lelang Mercari/Yahoo Auction siap tampung',
  },
];
